# -*- coding: utf-8 -*-
"""exoplanet_visualizer_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGllZhWHComl78FCGJ6njRrklxdOWPyY

# Habitable Exoplanets within 50 ly
"""

# Install necessary packages
!pip install pandas plotly

import math
import pandas as pd
import plotly.express as px

# Sample exoplanet data
data = [
    {"name": "Teegarden's Star b", "ra": 42.4646, "dec": 16.9186, "distance": 12.5, "habitability": 0.97},
    {"name": "TRAPPIST-1 d", "ra": 348.6227, "dec": -5.0413, "distance": 40.5, "habitability": 0.91},
    {"name": "Proxima Centauri b", "ra": 217.4290, "dec": -62.6794, "distance": 4.2, "habitability": 0.86},
    {"name": "GJ 1002 b", "ra": 37.3796, "dec": -7.5930, "distance": 15.8, "habitability": 0.86},
    {"name": "GJ 1061 d", "ra": 61.0492, "dec": -46.6690, "distance": 12, "habitability": 0.86},
    {"name": "GJ 1061 c", "ra": 61.0492, "dec": -44.6690, "distance": 12, "habitability": 0.86},
    {"name": "Ross 128 b", "ra": 177.1154, "dec": 0.0237, "distance": 11, "habitability": 0.86},
    {"name": "GJ 273 b", "ra": 114.7048, "dec": 5.2250, "distance": 12.3, "habitability": 0.85},
    {"name": "Wolf 1069 b", "ra": 217.4652, "dec": 14.1276, "distance": 31.3, "habitability": 0.85},
    {"name": "TRAPPIST-1 e", "ra": 344.6227, "dec": -5.0413, "distance": 40.5, "habitability": 0.85},
    {"name": "GJ 667 C f", "ra": 261.7458, "dec": -34.9961, "distance": 23.6, "habitability": 0.76},
    {"name": "TRAPPIST-1 f", "ra": 342.6227, "dec": -5.0413, "distance": 40.5, "habitability": 0.68},
    {"name": "Teegarden's Star c", "ra": 44.4646, "dec": 16.9186, "distance": 12.5, "habitability": 0.66},
    {"name": "GJ 669 C e", "ra": 259.7458, "dec": -34.9961, "distance": 23.6, "habitability": 0.60},
    {"name": "GJ 1002 c", "ra": 39.3796, "dec": -7.5930, "distance": 15.8, "habitability": 0.58},
    {"name": "TRAPPIST-1 g", "ra": 346.6227, "dec": -5.0413, "distance": 40.5, "habitability": 0.58},

]

# Convert RA/Dec/Distance to Cartesian coordinates
def ra_dec_to_xyz(ra_deg, dec_deg, distance_ly):
    ra_rad = math.radians(ra_deg)
    dec_rad = math.radians(dec_deg)
    x = distance_ly * math.cos(dec_rad) * math.cos(ra_rad)
    y = distance_ly * math.cos(dec_rad) * math.sin(ra_rad)
    z = distance_ly * math.sin(dec_rad)
    return x, y, z

for d in data:
    x, y, z = ra_dec_to_xyz(d["ra"], d["dec"], d["distance"])
    d["x"] = x
    d["y"] = y
    d["z"] = z

df = pd.DataFrame(data)


fig = px.scatter_3d(
    df,
    x="x", y="y", z="z",
    color="habitability",
    color_continuous_scale=[(0, "#8B0000"), (0.5, "#FFD700"), (1, "#00FF00")],
    range_color=[0, 1],
    hover_name="name",
    hover_data={"distance": True, "habitability": True},
    title="Habitable Exoplanets Within 50 Light-Years",
)

fig.update_traces(marker=dict(size=6))
fig.update_layout(
    template="plotly_dark",  # Set dark mode
    scene=dict(xaxis_title="X (ly)", yaxis_title="Y (ly)", zaxis_title="Z (ly)"),
    coloraxis_colorbar=dict(title="Habitability (0–1)", tickvals=[0, 0.5, 1]),
)
fig.show()